server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
#    org.springframework.boot.autoconfigure: DEBUG


oauth2:
  resource:
    services:
      service-a:
        uri: http://localhost:9000/service-a
      service-b:
        uri: http://localhost:9001/service-b
