server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
#    org.springframework.boot.autoconfigure: DEBUG

spring:
  security:
    oauth2:
      client:
        registration:
          login-client:
            provider: uaa
            client-id: login-client
            client-secret: secret
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid,profile,email
          client-abc:
            provider: uaa
            client-id: client-abc
            client-secret: secret
            redirect-uri: "{baseUrl}/flow-abc"
            scope: authority-a,authority-b,authority-c
        provider:
          uaa:
            issuer-uri: http://localhost:8090/uaa/oauth/token

oauth2:
  resource:
    services:
      service-a:
        uri: http://localhost:9000/service-a
      service-b:
        uri: http://localhost:9001/service-b
